### PR TITLE
:lock: Change on authorization role for getAll and getOne

### PR DESCRIPTION
**Pull request by VillanuevaFer**
Security issue due to Broken Access Control on UserController.java
Changed required role from ROLE_USER to ROLE_ADMIN on `/v1/users` and` /v1/users/{userId}` endpoints.
It's possible to obtain sensitive information just by making a GET request on any of those endpoints by setting the Authorization header from a non-admin user. 

Also, please note that this pull request is part of a project for a university subject, so I'd really appreciate if you could review and approve it if you consider it useful.

### CODE REVIEW

**Comment by loicgreffier** [comment]
Hi @VillanuevaFer, thank you for contributing. 

Simple users have to access `GET /v1/users` at it is used to add new users to a dashboard. Restricting `/v1/users` to admin will break this feature. Also, these endpoints do not expose user sensitive data (such as racial, ethnic origin, political opinions, religious or philosophical beliefs, genetic or health-related data) consequently we can keep them accessible from simple users

**Comment by VillanuevaFer** [comment]
Hey @loicgreffier, with sensitive data I meant security-wise sensitive data, since attributes such as roles, emails,  usernames.

**Comment by loicgreffier** [comment]
In this case, the solution would be: 
- A `GET /v1/admin/users` endpoint (corresponding to the current `/v1/users`) that exposes required data for admin (including username, emails, roles, etc... through a `AdminUserResponseDto`). This endpoint shoud be the one called from the admin/users menu.
-  A `GET /v1/users` endpoint that exposes required data for non-admin (firstname, lastname, username, etc... through a `UserResponseDto`. Emails and roles can be omitted here. Usernames are required to be accessible for non-admin users as it is part of our internal functioning.). This endpoint should be the one called from the auto-completion menu when adding a new user to a dashboard.

Same implementation should be done for `GET /v1/admin/users/{userId}` and `GET /v1/users/{userId}`.

**Comment by loicgreffier** [comment]
Linked with #710

**Pull request closed without merging**
